### ISSUE TITLE
Db Kayıt Tarihi bilgileri serverdan alınacak

### ISSUE THREAD

**Issue by gokmenyilmaz** [esero/EvrakArsiv#6]
Kullanıcının makinasının saati yanlış olabilir yada değiştirerek programı hacklayeblir
o yüzden server saati kullanılacak. Örneği aşağıda

var dQuery = dbContext.CreateQuery<DateTime>("CurrentDateTime() ");
DateTime dbDate = dQuery.AsEnumerable().First();

sql karşılığı:
SELECT GetDate() AS [C1] FROM  ( SELECT cast(1 as bit) AS X ) AS [SingleRowTable1]

**Comment by esero** [comment]
tamamlandı
