### ISSUE TITLE
Cevap evrak sayısı

### ISSUE THREAD

**Issue by esero** [esero/EvrakArsiv#8]
Sıralama yapınca sayılar sapıtıyor

**Comment by gokmenyilmaz** [comment]
yazınca düzeldi... 
<DataTemplate>
                                    <StackPanel Visibility="{Binding  RowData.Row.CevapSayısı, Converter={StaticResource NumberVisibilityConverter}}">
                                        <Border Background="Green" Margin="3,4,3,3" BorderBrush="Red" CornerRadius="5" 
                                                >
                                            <TextBlock Foreground="White" FontSize="10" TextAlignment="Center" FontWeight="Bold" 
                                                       Text="{Binding Path=Data.CevapSayısı}"></TextBlock>
                                        </Border>
                                    </StackPanel>
                                </DataTemplate>

**Comment by gokmenyilmaz** [comment]
converter yeni hali bu...  
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
         

            if (value.ToString()== "0")
               return Visibility.Hidden;
            else
                return Visibility.Visible;
        }

**Comment by esero** [comment]
hallettim
